server:
  port: 9999
spring:
  application:
    name: authorization-server
  cloud:
    nacos:
      discovery:
        server-addr: nacos-server:8848
  datasource:
    url: jdbc:mysql://localhost:3306/coinhub?useSSL=false&serverTimezon=GMT%28
    username: root
    password: 20010419
    driver-class-name: com.mysql.cj.jdbc.Driver
#  redis:
#    host: redis-server
#    port: 6379
#    password: 20010419